In [34]:
import numpy as np
import statistics

importing pertinent packages for vectorization(numpy) and for statistics


In [35]:
def max_division(x):

    max_value=max(x)
    normalized=np.array(x)/max_value  # deviding each element over maximum value of feature
    return normalized

In [36]:
data=[100,154,254,657]
stn=max_division(data)
print(stn)

[0.152207   0.23439878 0.38660578 1.        ]


In [37]:
def mean_normalization(x):

    min_value=min(x) # getting the minimum value of feature
    max_value=max(x) # getting the maximum value of feature
    mean = sum(x) / len(x) # calculate the mean of feature

    normalized=(np.array(x)-mean)/(max_value-min_value)
    return  normalized




In [38]:
data=[10,15,4,78,44]
x=mean_normalization(data)
print(x)

[-0.27297297 -0.20540541 -0.35405405  0.64594595  0.18648649]


In [39]:

def z_score(x):

    mean = sum(x) / len(x)
    deviation = statistics.stdev(x) # getting the deviation of feature's data
    normalized=(np.array(x)-mean)/deviation
    return normalized


In [40]:
data=[111,545,789,412,451,120]
x=z_score(data)
print(x)


[-1.13136094  0.540639    1.4806574   0.02825192  0.17850076 -1.09668813]


In [41]:
def normalized(x,norm_type='z_score'): # the function for normalizing the data based on the type of normalization
    if norm_type=='max_division':
       max_value=max(x)
       normalized=np.array(x)/max_value
    elif norm_type==' mean_normalization':
         min_value=min(x)
         max_value=max(x)
         mean = sum(x) / len(x)
         normalized=(np.array(x)-mean)/(max_value-min_value)
    elif norm_type=='z_score':
         mean = sum(x) / len(x)
         deviation = statistics.stdev(x)
         normalized=(np.array(x)-mean)/deviation
    return normalized

In [42]:
x=range(10)
test=normalized(x,norm_type='max_division')
test

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])